//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int Rental_ID { get; set; }
        public int Tenant_ID { get; set; }
        public int Employee_ID { get; set; }
        public string Pavilion_Number { get; set; }
        public string Status_rent { get; set; }
        public System.DateTime The_Beginning_of_the_Lease { get; set; }
        public System.DateTime End_of_Lease { get; set; }
        public int Shopping_center_ID { get; set; }
    
        public virtual Pavilion Pavilion { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
