//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_center
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shopping_center()
        {
            this.Pavilion = new HashSet<Pavilion>();
        }
    
        public int Shopping_center_ID { get; set; }
        public string Title { get; set; }
        public string Status_center { get; set; }
        public Nullable<int> Pavilion_Number { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<double> The_Coefficient_Of_Added_Value { get; set; }
        public Nullable<int> Number_of_floors { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilion> Pavilion { get; set; }
    }
}
